name: check-proxies-schedule

on:
  schedule:
   - cron: "0 */6 * * *"

jobs:
  check-row-urls:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: check urls
        run: python checkProxies.py
        shell: bash
